// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryMG9mf-zjMXEe1aFI5vgFH1VBrZ1Ilc',
    appId: '1:592018871802:web:7f8eeaa69e4b2dc6d4c043',
    messagingSenderId: '592018871802',
    projectId: 'restore-5cfcb',
    authDomain: 'restore-5cfcb.firebaseapp.com',
    storageBucket: 'restore-5cfcb.firebasestorage.app',
    measurementId: 'G-S3FWTNL2DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65W4ocJQnG7twPlaFcIo9TX9hm03pDas',
    appId: '1:592018871802:android:385fc9fcf8874ab8d4c043',
    messagingSenderId: '592018871802',
    projectId: 'restore-5cfcb',
    storageBucket: 'restore-5cfcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lG3tfoADJyZdUDNToauExv4Tzu1GXBw',
    appId: '1:592018871802:ios:fdcea2965bf97425d4c043',
    messagingSenderId: '592018871802',
    projectId: 'restore-5cfcb',
    storageBucket: 'restore-5cfcb.firebasestorage.app',
    iosBundleId: 'com.example.restore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lG3tfoADJyZdUDNToauExv4Tzu1GXBw',
    appId: '1:592018871802:ios:fdcea2965bf97425d4c043',
    messagingSenderId: '592018871802',
    projectId: 'restore-5cfcb',
    storageBucket: 'restore-5cfcb.firebasestorage.app',
    iosBundleId: 'com.example.restore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAryMG9mf-zjMXEe1aFI5vgFH1VBrZ1Ilc',
    appId: '1:592018871802:web:69a83ab5b7c83c4cd4c043',
    messagingSenderId: '592018871802',
    projectId: 'restore-5cfcb',
    authDomain: 'restore-5cfcb.firebaseapp.com',
    storageBucket: 'restore-5cfcb.firebasestorage.app',
    measurementId: 'G-H0R29QQ2VD',
  );
}
